### PR TITLE
Fixing the minor niggles with the unlock register. Also can run witho…

### PR DESCRIPTION
**Pull request by terriblefire**
Noticed i should have been setting the WREL before calling unlock (by comparing with flashrom). 

Also switched to using gpiomem so i dont need to sudo just to flash a chip.

### CODE REVIEW

**Comment by terriblefire** [comment]
To explain the change a bit more. The change to the unlock function is something I messed up in my original PR for the global unlock mechanism. That will not affect anyone unless they specify -u on the commandline

The second change is fixing a minor bug in the program where we need to use sudo and access a more broad resource than we need to. 

**The difference between the two is that /dev/mem allows access to all ARM accessible memory on the Pi, whilst /dev/gpiomem is just the area associated with GPIO control**.

I believe we want this in fomu-flash. 

https://forums.raspberrypi.com/viewtopic.php?t=167446#:~:text=The%20difference%20between%20the%20two,area%20associated%20with%20GPIO%20control.

**Comment by xobs** [comment]
Thanks for the patch! Would you mind modifying it so it first tries to open `/dev/mem`, and then falls back to `/dev/gpiomem` if that fails? That way it will work on systems that don't have `/dev/gpiomem` (which, admittedly, are increasingly rare...)

**Comment by terriblefire** [comment]
Even trying /dev/mem is an unnecessary security flaw in formu-flash. Using the correct device reduces the attack surface.

Do you have a good reason to be using /dev/mem over /dev/gpiomem? Is there a need to access all the memory space on the pi rather than just the gpio space?

Falling back like this also adds unnecessary cyclomatic complexity to the software and potentially doubles the testing required.

**Comment by xobs** [comment]
How is it a security flaw to try `/dev/mem` as a fallback?

I'd like to have the fallback there for people who are running on older kernels, or on distros that don't provide `/dev/gpiomem`. As an example, we merged support for the Raspberry Pi Model A at some point because someone was using that.

I also ran this on Fedberry for a while because it had better support for readonly root, and that didn't provide `/dev/gpiomem` whereas it did provide `/dev/mem`.

A workaround in the case where `/dev/gpiomem` doesn't exist would be to symlink `/dev/mem` to `/dev/gpiomem` and run it as sudo, which might also be fine.

**Comment by terriblefire** [comment]
Because you didnt ask me to use /dev/mem as a fallback. You asked me to use gpiomem as a fallback.

**Pull request closed without merging**
